---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: demos-stripprefix@kubernetescrd
spec:
  ingressClassName: kommander-traefik
  rules:
  - http:
      paths:
      - path: /demos/sockshop
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
      - path: /catalogue
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: demos-stripprefix
  namespace: kommander
spec:
  stripPrefix:
    prefixes:
      - "/demos/sockshop"
    forceSlash: false
